#!venv/bin/python3

import sys, os

envKey = "OBIESOURCEBOTTOKEN"

token = os.environ.get(envKey)

if token == None: # not defined
    print(f"{envKey}=<secret token> {sys.argv[0]}")
    sys.exit(1)

import discord

bot = discord.Bot()

# --------------------
# COMMANDS
# --------------------

@bot.slash_command()
async def resources(ctx):
    await ctx.respond("resource stuff here")

@bot.slash_command()
async def hello(ctx, name: str = None, color: str = None):
    await ctx.respond(f"Hello, {name}! Your favorite color is {color}.")

bot.run(token)
